theme: minima
title: Group 2's YouTube Channel Website
author: Jacob Tuico, Noly Alabado, Sebastian Tato, Janiah Pilares, Martel Hennessy
description: A website about our theoretical YouTube Channel for our LifeLabs IPBA
